# tell travis we need docker running
sudo: required
services:
  - docker

# tell travis to build using dockerfile.dev in current directory
before_install:
  - docker build -t cli333/docker-react -f Dockerfile.dev .

# travis runs test and exits
script:
  - docker run cli333/docker-react npm run test -- --coverage
